server:
  port: 9000
logging:
  level:
    com.kratosgado.meeapp: DEBUG
    org.springframework: WARN
spring:
  application:
    name: meeapp
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:meeapp}
    username: ${DB_USERNAME:kratosgado}
    password: ${DB_PASSWORD:28935617}
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
      default_schema: app_schema
  liquibase:
    enabled: true
    # url: ${spring.datasource.url}
    # user: ${spring.datasource.url}
    # password: ${spring.datasource.password}
    # change-log: filesystem:gradle/liquibase/changelog/db.changelog-master.sql
    change-log: classpath:db/changelog/db.changelog-master.sql
    default_schema: app_schema
    # hibernate:
    #   dialect: org.hibernate.dialect.PostgreSQLDialect
    # diff-change-log-file: gradle/liquibase/changelog/changes/V${version}__${description}.sql
    # diff-types: tables,columns,indexes,foreignkeys,primarykeys,uniqueconstraints
    parameters:
      environment: dev
    contexts: ${spring.profiles.active:dev}
springdoc:
  api-docs:
    path: /docs/api-docs
  swagger-ui:
    path: /docs/swagger-ui.html
    operations-sorter: method
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:940ff3dce8ce688ebb9cd5c866cedd3b3d423d5ca31342d06402569949991832}
    expiration-time: ${JWT_EXPIRATION_TIME:36000000}
