@baseurl =localhost:9000/api/auth


POST {{baseurl}}/signup
Content-Type: application/json

{
	"email": "kratosgado@gmail.com",
	"password": "28935617",
	"name": "kratosgado"
}

###
POST {{baseurl}}/login
Content-Type: application/json

{
	"email": "kratosgado@gmail.com",
	"password": "28935617"
}

# @lang
> {%
const data = response.body;
client.global.set("token", data.token);
%}
