@baseurl =localhost:9000/api/groups


POST {{baseurl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"name": "Philosophy"
}

###
# @name get groups
GET {{baseurl}}
Authorization: Bearer {{token}}

###
# @name get groups
POST {{baseurl}}/join/433351e3-760f-4be7-891f-d1e0a4fda7d7
Authorization: Bearer {{token}}
