@baseurl =localhost:9000/api

# @name get users
GET {{baseurl}}/users
Authorization: Bearer dfkljdf

###
# @name create user
POST {{baseurl}}/users
Authorization: Bearer dfkljdf
Content-Type: application/json

{
	"email": "gado@gmail.com",
	"name": "Gado"
}

###
# @name get user
GET {{baseurl}}/users/2
